language: rust
cache: cargo
sudo: false

before_script:
  - |
    LATEST=$(cargo search mdbook | grep "^mdbook =" | cut -d '"' -f 2)
    INSTALLED=$(cargo install --list | grep "^mdbook " | cut -d v -f 2 | tr -d :)
    if [ "$INSTALLED" != "$LATEST" ]; then
      if [ "$INSTALLED" != "" ]; then
        echo "mdbook '$INSTALLED' is already installed"
      fi
      echo "Installing mdbook '$LATEST'"
      cargo install mdbook --force --vers "$LATEST"
    fi
    LATEST=$(cargo search mdbook-checklist | grep "^mdbook-checklist =" | cut -d '"' -f 2)
    INSTALLED=$(cargo install --list | grep "^mdbook-checklist " | cut -d v -f 2 | tr -d :)
    if [ "$INSTALLED" != "$LATEST" ]; then
      if [ "$INSTALLED" != "" ]; then
        echo "mdbook-checklist '$INSTALLED' is already installed"
      fi
      echo "Installing mdbook-checklist '$LATEST'"
      cargo install mdbook-checklist --force --vers "$LATEST"
    fi

script:
  - mdbook build
  - mdbook test


jobs:
  include:
    - stage: 'nightly'
      rust: nightly
    - stage: 'stable'
      rust: stable
      deploy:
        provider: pages
        target-branch: gh-pages
        local-dir: book
        skip-cleanup: true
        github-token: $GITHUB_TOKEN
        keep-history: true
        on:
          branch: master
